import turtle

tar = turtle.Turtle()
window = turtle.Screen()
window.bgcolor("#B0BF1A")
tar.shape("turtle")
tar.width(5)
tar.color("green")
window.setup(1333,760)

class AL:
    def A():
        tar.speed(1)
        tar.penup()
        tar.fd(50)
        tar.left(180)
        tar.fd(35)
        tar.right(108.29)
        tar.pendown()
        tar.fd(105.95)
        tar.right(141.42)
        tar.fd(105.95)
        tar.bk(35)
        tar.right(108.29)
        tar.fd(46.88)
        tar.penup()
        tar.left(90)
        tar.fd(33.04)
        tar.left(90)
        tar.fd(75.44)
        tar.pendown()

    def B():
        tar.speed(1)
        tar.penup()
        tar.fd(50)
        tar.left(180)
        tar.pendown()
        tar.fd(35)
        tar.right(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(70)
        tar.right(90)
        tar.fd(50)
        tar.right(90)
        tar.fd(70)
        tar.bk(70)
        tar.left(90)
        tar.fd(50)
        tar.right(90)
        tar.fd(35)
        tar.penup()
        tar.bk(35)
        tar.right(180)
        tar.fd(30)
        tar.pendown()

    def C():
        tar.speed(1)
        tar.left(180)
        tar.fd(35)
        tar.right(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(70)
        tar.right(90)
        tar.penup()
        tar.fd(100)
        tar.right(90)
        tar.pendown()
        tar.fd(35)
        tar.penup()
        tar.bk(45)
        tar.right(180)
        tar.fd(20)
        tar.pendown()

    def D():
        tar.speed(1)
        tar.penup()
        tar.fd(50)
        tar.pendown()
        tar.left(180)
        tar.fd(35)
        tar.right(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(70)
        tar.right(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(35)
        tar.penup()
        tar.bk(35)
        tar.right(180)
        tar.fd(20)
        tar.pendown()

    def E():
        tar.speed(1)
        tar.penup()
        tar.fd(20)
        tar.pendown()
        tar.fd(35)
        tar.bk(70)
        tar.left(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(70)
        tar.penup()
        tar.right(90)
        tar.fd(50)
        tar.right(90)
        tar.pendown()
        tar.fd(70)
        tar.penup()
        tar.left(90)
        tar.fd(60)
        tar.left(90)
        tar.fd(80)
        tar.pendown()

    def F():
        tar.speed(1)
        tar.left(180)
        tar.penup()
        tar.fd(35)
        tar.right(90)
        tar.pendown()
        tar.fd(100)
        tar.right(90)
        tar.fd(70)
        tar.penup()
        tar.bk(20)
        tar.right(90)
        tar.fd(40)
        tar.right(90)
        tar.pendown()
        tar.fd(50)
        tar.penup()
        tar.left(90)
        tar.fd(60)
        tar.left(90)
        tar.fd(100)
        tar.pendown()

    def G():
        tar.speed(1)
        tar.penup()
        tar.fd(35)
        tar.left(90)
        tar.fd(100)
        tar.left(90)
        tar.pendown()
        tar.fd(70)
        tar.left(90)
        tar.fd(100)
        tar.left(90)
        tar.fd(70)
        tar.left(90)
        tar.fd(40)
        tar.left(90)
        tar.fd(35)
        tar.penup()
        tar.left(90)
        tar.fd(40)
        tar.left(90)
        tar.fd(45)
        tar.pendown()

    def H():
        tar.speed(1)
        tar.penup()
        tar.fd(40)
        tar.pendown()
        tar.left(90)
        tar.fd(100)
        tar.bk(50)
        tar.left(90)
        tar.fd(50)
        tar.right(90)
        tar.fd(50)
        tar.bk(100)
        tar.penup()
        tar.right(90)
        tar.fd(90)
        tar.pendown()

    def I():
        tar.speed(1)
        tar.left(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(5)
        tar.bk(10)
        tar.fd(5)
        tar.right(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(5)
        tar.bk(10)
        tar.penup()
        tar.bk(10)
        tar.right(180)
        tar.fd(15)
        tar.pendown()

    def J():
        tar.speed(1)
        tar.penup()
        tar.left(180)
        tar.fd(35)
        tar.right(90)
        tar.fd(100)
        tar.right(90)
        tar.pendown()
        tar.fd(70)
        tar.right(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(60)
        tar.right(90)
        tar.fd(35)
        tar.penup()
        tar.bk(35)
        tar.right(90)
        tar.fd(70)
        tar.pendown()

    def K():
        tar.speed(1)
        tar.penup()
        tar.fd(40)
        tar.left(180)
        tar.fd(35)
        tar.right(90)
        tar.pendown()
        tar.fd(100)
        tar.bk(50)
        tar.right(45)
        tar.fd(70)
        tar.bk(70)
        tar.right(90)
        tar.fd(70)
        tar.penup()
        tar.left(45)
        tar.fd(30)

    def L():
        tar.speed(1)
        tar.penup()
        tar.fd(40)
        tar.left(180)
        tar.fd(35)
        tar.right(90)
        tar.fd(100)
        tar.pendown()
        tar.bk(100)
        tar.right(90)
        tar.fd(70)
        tar.penup()
        tar.fd(20)

    def M():
        tar.left(90)
        tar.fd(100)
        tar.right(150)
        tar.fd(45)
        tar.left(120)
        tar.fd(45)
        tar.right(150)
        tar.fd(100)
        tar.penup()
        tar.left(90)
        tar.fd(20)
        tar.pendown()

    def N():
        tar.left(90)
        tar.fd(100)
        tar.right(145)
        tar.fd(122)
        tar.left(145)
        tar.fd(100)
        tar.penup()
        tar.backward(100)
        tar.right(90)
        tar.fd(20)
        tar.pendown()

    def O():
        tar.penup()
        tar.fd(40)
        tar.pendown()
        for i in range(36):
            tar.fd(9)
            tar.left(10)
        tar.penup()
        tar.fd(90)
        tar.pendown()

    def P():
        tar.speed(1)
        tar.left(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(70)
        tar.right(90)
        tar.fd(55)
        tar.right(90)
        tar.fd(70)

        tar.penup()
        tar.left(90)
        tar.forward(50)
        tar.left(90)
        tar.fd(90)
        tar.pendown()

    def Q():
        tar.left(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(70)
        tar.right(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(70)
        tar.bk(70)
        tar.left(130)
        tar.fd(10)
        tar.bk(20)
        tar.penup()
        tar.fd(10)
        tar.left(50)
        tar.fd(30)
        tar.pendown()

    def R():
        tar.left(90)
        tar.fd(100)
        tar.right(90)
        tar.fd(70)
        tar.right(90)
        tar.fd(50)
        tar.right(90)
        tar.fd(70)
        tar.bk(20)
        tar.left(135)
        tar.fd(70)
        tar.penup()
        tar.left(45)
        tar.fd(30)
        tar.pendown()

    def S():
        tar.speed(1)
        tar.left(90)
        tar.penup()
        tar.fd(100)
        tar.right(90)
        tar.pendown()
        tar.fd(70)
        tar.back(70)
        tar.right(90)
        tar.fd(50)
        tar.left(90)
        tar.fd(70)
        tar.right(90)
        tar.fd(50)
        tar.right(90)
        tar.fd(70)
        tar.right(180)
        tar.penup()
        tar.fd(100)
        tar.pendown()

    def T():
        tar.penup()
        tar.fd(30)
        tar.pendown()
        tar.left(90)
        tar.fd(103)
        tar.right(90)
        tar.fd(35)
        tar.bk(70)
        tar.penup()
        tar.right(90)
        tar.fd(100)
        tar.left(90)
        tar.fd(100)
        tar.pendown()

    def U():
        tar.speed(1)
        tar.left(90)
        tar.penup()
        tar.fd(122)
        tar.right(180)
        tar.pendown()
        tar.fd(78)

        for i in range(22):
            tar.fd(6)
            tar.left(8)
        tar.left(6)
        tar.fd(88)
        tar.penup()
        tar.right(180)
        tar.fd(122)
        tar.left(88)
        tar.fd(30)
        tar.pendown()

    def V():
        tar.speed(1)
        tar.penup()
        tar.fd(20)
        tar.pendown()
        tar.left(112)
        tar.fd(100)
        tar.bk(100)
        tar.right(45)
        tar.fd(102)
        tar.right(158)
        tar.penup()
        tar.fd(94)
        tar.left(90)
        tar.fd(20)
        tar.pendown()

    def W():
        tar.speed(1)
        tar.left(95)
        tar.fd(100)
        tar.bk(100)
        tar.right(15)
        tar.fd(102)

        tar.right(160)
        tar.fd(100)
        tar.left(165)
        tar.forward(100)
        tar.penup()
        tar.right(175)
        tar.fd(100)
        tar.left(90)
        tar.fd(20)
        tar.pendown()

    def X():
        tar.speed(1)
        tar.penup()
        tar.fd(20)
        tar.pendown()
        tar.left(90)
        tar.penup()
        tar.fd(70)
        tar.pendown()
        tar.right(135)
        tar.forward(100)
        tar.left(135)
        tar.penup()
        tar.forward(70)
        tar.pendown()
        tar.left(135)
        tar.forward(100)
        tar.penup()
        tar.left(135)
        tar.fd(100)
        tar.pendown()

    def Y():
        tar.speed(1)
        tar.left(90)
        tar.penup()
        tar.fd(50)
        tar.pendown()
        tar.left(35)
        tar.fd(50)
        tar.bk(50)
        tar.right(70)
        tar.fd(52)
        tar.back(52)
        tar.right(145)
        tar.forward(50)
        tar.penup()
        tar.left(90)
        tar.fd(45)
        tar.pendown()

    def Z():
        tar.speed(1)
        tar.left(90)
        tar.penup()
        tar.fd(100)
        tar.right(90)
        tar.pendown()
        tar.fd(70)
        tar.right(135)
        tar.forward(135)
        tar.left(135)
        tar.forward(70)
        tar.penup()
        tar.fd(40)
        tar.pendown()


a = "Aa"; b = "Bb"; c = "Cc"; d = "Dd"; e = "Ee"; f = "Ff"; g = "Gg"; h = "Hh"; i = "Ii";j = "Jj";k = "Kk"; l = "Ll"; m = "Mm"; n = "Nn"; o = "Oo"
pp = "Pp"; q = "Qq"; r = "Rr"; s = "Ss"; t = "Tt"; u = "Uu"; v = "Vv"; w = "Ww"; x = "Xx"; y = "Yy"; z = "Zz"; others = " 0123456789.!@#$%^&*()-_<>,;:""=[]{}()"

User_input = str(input("your name: "))
for p in User_input:
    if p in a:
        print(AL.A())
    elif p in b:
        print(AL.B())
    elif p in c:
        print(AL.C())
    elif p in d:
        print(AL.D())
    elif p in e:
        print(AL.E())
    elif p in f:
        print(AL.F())
    elif p in g:
        print(AL.G())
    elif p in h:
        print(AL.H())
    elif p in i:
        print(AL.I())
    elif p in j:
        print(AL.J())
    elif p in k:
        print(AL.K())
    elif p in l:
        print(AL.L())
    elif p in m:
        print(AL.M())
    elif p in n:
        print(AL.N())
    elif p in o:
        print(AL.O())
    elif p in pp:
        print(AL.P())
    elif p in q:
        print(AL.Q())
    elif p in r:
        print(AL.R())
    elif p in s:
        print(AL.S())
    elif p in t:
        print(AL.T())
    elif p in u:
        print(AL.U())
    elif p in v:
        print(AL.V())
    elif p in w:
        print(AL.W())
    elif p in x:
        print(AL.X())
    elif p in y:
        print(AL.Y())
    elif p in z:
        print(AL.Z())
    elif p in others:
        tar.hideturtle()
        tar.penup()
        tar.write("PLEASE ONLY UPPERCASE ALPHABET!!!", font=("Arial", 20, "normal"))
    else:
        print("INVALID")

window.exitonclick()

#tar.getscreen()._root.mainloop()
