import turtle

def S():

    tar = turtle.Turtle()
    tar.shape("turtle")
    window = turtle.Screen()
    window.bgcolor("red")
    tar.width(5)
    tar.color("green")
    tar.speed(1)

    tar.left(90)
    tar.penup()
    tar.fd(100)
    tar.right(90)
    tar.pendown()
    tar.fd(70)
    tar.back(70)
    tar.right(90)
    tar.fd(50)
    tar.left(90)
    tar.fd(70)
    tar.right(90)
    tar.fd(50)
    tar.right(90)
    tar.fd(70)
    tar.right(180)
    tar.penup()
    tar.fd(100)
    tar.pendown()
    window.exitonclick()
S()